#**ETL DATASET AVES**


---

#Carga de archivo

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import re, os, unicodedata

# Montar Google Drive para acceder al archivo
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Ruta del archivo en Google Drive
# Asegúrate de que la ruta sea correcta.
DATA_DIR = '/content/drive/MyDrive/Proyectos/Aves'

PATH_INPUT = f'{DATA_DIR}/dataset-2025.csv'  # must contain latitude, longitude
PATH_OUTPUT = f'{DATA_DIR}/dataset-2025-definitivo.csv'

# Cargar el archivo CSV en un DataFrame de pandas
try:
    df = pd.read_csv(PATH_INPUT, sep='\t', engine='python')
    df_copy = df.copy(deep=True)
    print("Archivo cargado exitosamente.")
    print(df.head()) # Mostrar las primeras filas del DataFrame
    print(df.describe())
    print(df.info())
except FileNotFoundError:
    print(f"Error: El archivo no se encontró en la ruta especificada: {PATH_INPUT}")
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")

Mounted at /content/drive
Archivo cargado exitosamente.
       gbifID                            datasetKey  \
0  5858379769  e3ce628e-9683-4af7-b7a9-47eef785d3bb
1  5858386191  e3ce628e-9683-4af7-b7a9-47eef785d3bb
2  5063633106  50c9509d-22c7-4a22-a47d-8c48425ef4a7
3  5230239878  50c9509d-22c7-4a22-a47d-8c48425ef4a7
4  5838274528  50c9509d-22c7-4a22-a47d-8c48425ef4a7

                                        occurrenceID   kingdom    phylum  \
0               24d7b1a0-7301-4c0f-9e84-de21eb545ef6  Animalia  Chordata
1               f7d4c062-2e59-4029-ba6a-b3004e920df5  Animalia  Chordata
2  https://www.inaturalist.org/observations/26024...  Animalia  Chordata
3  https://www.inaturalist.org/observations/29764...  Animalia  Chordata
4  https://www.inaturalist.org/observations/31784...  Animalia  Chordata

  class              order        family         genus  \
0  Aves  Procellariiformes   Diomedeidae      Diomedea
1  Aves  Procellariiformes   Diomedeidae      Diomedea
2  Aves      Passeriformes  Fringillidae        Spinus
3  Aves        Apodiformes   Trochilidae  Leucochloris
4  Aves      Passeriformes     Parulidae     Setophaga

                   species  ...  \
0      Diomedea epomophora  ...
1         Diomedea exulans  ...
2      Spinus magellanicus  ...
3  Leucochloris albicollis  ...
4      Setophaga pitiayumi  ...

                                        identifiedBy       dateIdentified  \
0  <a href=https://bee.questagame.com/#/profile/2...                  NaN
1  <a href=https://bee.questagame.com/#/profile/4...                  NaN
2                                      Silvia Mallet  2025-02-01T11:20:21
3                                  Mariano Cosentino  2025-07-13T17:33:05
4                                    Nicolas Olejnik  2025-09-30T20:16:23

        license       rightsHolder  \
0  CC_BY_NC_4_0                NaN
1  CC_BY_NC_4_0                NaN
2  CC_BY_NC_4_0      Silvia Mallet
3     CC_BY_4_0  Mariano Cosentino
4     CC_BY_4_0    Nicolas Olejnik

                                          recordedBy typeStatus  \
0  <a href='https://bee.questagame.com/#/profile/...        NaN
1  <a href='https://bee.questagame.com/#/profile/...        NaN
2                                      Silvia Mallet        NaN
3                                  Mariano Cosentino        NaN
4                                    Nicolas Olejnik        NaN

  establishmentMeans           lastInterpreted              mediaType  \
0                NaN  2026-01-15T20:36:37.084Z             StillImage
1                NaN  2026-01-15T20:36:20.354Z  StillImage;StillImage
2                NaN  2026-01-08T22:14:45.967Z             StillImage
3                NaN  2026-01-08T22:19:19.841Z             StillImage
4                NaN  2026-01-08T22:23:57.830Z             StillImage

                                               issue
0  SCIENTIFIC_NAME_ID_NOT_FOUND;TAXON_CONCEPT_ID_...
1  SCIENTIFIC_NAME_ID_NOT_FOUND;TAXON_CONCEPT_ID_...
2  COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
3  COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
4  COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...

[5 rows x 50 columns]
             gbifID  individualCount  decimalLatitude  decimalLongitude  \
count  8.513100e+04      1227.000000     85117.000000      85117.000000
mean   5.464758e+09         5.881826       -34.613112        -61.588894
std    3.640026e+08        20.260616         6.195853          4.107143
min    5.006691e+09         1.000000       -58.349908        -73.414066
25%    5.134512e+09         1.000000       -35.700165        -64.193962
50%    5.281902e+09         1.000000       -34.580802        -60.688779
75%    5.889316e+09         3.000000       -31.620593        -58.433305
max    5.938721e+09       500.000000       -22.013091        -25.449913

       coordinateUncertaintyInMeters  coordinatePrecision  elevation  \
count                   6.771400e+04                  0.0        0.0
mean                    4.493782e+03                  NaN        NaN
std                     4.568158e+04                  NaN        NaN
min                     1.000000e+00                  NaN        NaN
25%                     1.500000e+01                  NaN        NaN
50%                     1.390000e+02                  NaN        NaN
75%                     1.006000e+03                  NaN        NaN
max                     7.313813e+06                  NaN        NaN

       elevationAccuracy  depth  depthAccuracy           day         month  \
count                0.0    0.0            0.0  85131.000000  85131.000000
mean                 NaN    NaN            NaN     14.241698      6.585874
std                  NaN    NaN            NaN      8.924539      3.577901
min                  NaN    NaN            NaN      1.000000      1.000000
25%                  NaN    NaN            NaN      7.000000      3.000000
50%                  NaN    NaN            NaN     13.000000      7.000000
75%                  NaN    NaN            NaN     22.000000     10.000000
max                  NaN    NaN            NaN     31.000000     12.000000

          year      taxonKey    speciesKey  typeStatus  establishmentMeans
count  85131.0  8.513100e+04  8.349100e+04         0.0                 0.0
mean    2025.0  4.070515e+06  3.855090e+06         NaN                 NaN
std        0.0  2.483676e+06  2.290479e+06         NaN                 NaN
min     2025.0  2.986000e+03  2.473341e+06         NaN                 NaN
25%     2025.0  2.482673e+06  2.482673e+06         NaN                 NaN
50%     2025.0  2.491862e+06  2.491655e+06         NaN                 NaN
75%     2025.0  5.231103e+06  5.229693e+06         NaN                 NaN
max     2025.0  1.231336e+07  1.134537e+07         NaN                 NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85131 entries, 0 to 85130
Data columns (total 50 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   gbifID                            85131 non-null  int64
 1   datasetKey                        85131 non-null  object
 2   occurrenceID                      85069 non-null  object
 3   kingdom                           85131 non-null  object
 4   phylum                            85131 non-null  object
 5   class                             85131 non-null  object
 6   order                             85131 non-null  object
 7   family                            85131 non-null  object
 8   genus                             85114 non-null  object
 9   species                           83491 non-null  object
 10  infraspecificEpithet              1051 non-null   object
 11  taxonRank                         85131 non-null  object
 12  scientificName                    85131 non-null  object
 13  verbatimScientificName            85131 non-null  object
 14  verbatimScientificNameAuthorship  3 non-null      object
 15  countryCode                       85131 non-null  object
 16  locality                          1917 non-null   object
 17  stateProvince                     84608 non-null  object
 18  occurrenceStatus                  85131 non-null  object
 19  individualCount                   1227 non-null   float64
 20  publishingOrgKey                  85131 non-null  object
 21  decimalLatitude                   85117 non-null  float64
 22  decimalLongitude                  85117 non-null  float64
 23  coordinateUncertaintyInMeters     67714 non-null  float64
 24  coordinatePrecision               0 non-null      float64
 25  elevation                         0 non-null      float64
 26  elevationAccuracy                 0 non-null      float64
 27  depth                             0 non-null      float64
 28  depthAccuracy                     0 non-null      float64
 29  eventDate                         85131 non-null  object
 30  day                               85131 non-null  int64
 31  month                             85131 non-null  int64
 32  year                              85131 non-null  int64
 33  taxonKey                          85131 non-null  int64
 34  speciesKey                        83491 non-null  float64
 35  basisOfRecord                     85131 non-null  object
 36  institutionCode                   83226 non-null  object
 37  collectionCode                    83281 non-null  object
 38  catalogNumber                     83281 non-null  object
 39  recordNumber                      2 non-null      object
 40  identifiedBy                      83089 non-null  object
 41  dateIdentified                    83086 non-null  object
 42  license                           85131 non-null  object
 43  rightsHolder                      84413 non-null  object
 44  recordedBy                        85130 non-null  object
 45  typeStatus                        0 non-null      float64
 46  establishmentMeans                0 non-null      float64
 47  lastInterpreted                   85131 non-null  object
 48  mediaType                         81256 non-null  object
 49  issue                             83947 non-null  object
dtypes: float64(12), int64(5), object(33)
memory usage: 32.5+ MB
None

# Eliminación de valores nulo y columnas no útiles

In [50]:
# Eliminar columnas con todos los valores nulos
df.dropna(axis=1, how='all', inplace=True)

# Eliminar columnas no útiles
df.drop(columns=['gbifID', 'datasetKey', 'occurrenceID', 'infraspecificEpithet',
                 'scientificName', 'countryCode', 'occurrenceStatus',
                 'publishingOrgKey', 'taxonKey', 'speciesKey',
                 'catalogNumber', 'identifiedBy', 'dateIdentified',
                 'license', 'rightsHolder', 'recordedBy', 'lastInterpreted',
                 'issue', 'recordNumber', 'verbatimScientificNameAuthorship'], inplace=True)

# Verificar las columnas restantes y sus valores no nulos
print("DataFrame después de eliminar columnas con todos los valores nulos:")
print(df.info())

DataFrame después de eliminar columnas con todos los valores nulos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85131 entries, 0 to 85130
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   kingdom                        85131 non-null  object
 1   phylum                         85131 non-null  object
 2   class                          85131 non-null  object
 3   order                          85131 non-null  object
 4   family                         85131 non-null  object
 5   genus                          85114 non-null  object
 6   species                        83491 non-null  object
 7   taxonRank                      85131 non-null  object
 8   verbatimScientificName         85131 non-null  object
 9   locality                       1917 non-null   object
 10  stateProvince                  84608 non-null  object
 11  individualCount                1227 non-null   float64
 12  decimalLatitude                85117 non-null  float64
 13  decimalLongitude               85117 non-null  float64
 14  coordinateUncertaintyInMeters  67714 non-null  float64
 15  eventDate                      85131 non-null  object
 16  day                            85131 non-null  int64
 17  month                          85131 non-null  int64
 18  year                           85131 non-null  int64
 19  basisOfRecord                  85131 non-null  object
 20  institutionCode                83226 non-null  object
 21  collectionCode                 83281 non-null  object
 22  mediaType                      81256 non-null  object
dtypes: float64(4), int64(3), object(16)
memory usage: 14.9+ MB
None

In [51]:
for columna in df.columns:
    conteo = df[columna].value_counts()
    print(f"\nConteo de valores en la columna '{columna}':")
    print(conteo)

Conteo de valores en la columna 'kingdom':
kingdom
Animalia    85131
Name: count, dtype: int64

Conteo de valores en la columna 'phylum':
phylum
Chordata    85131
Name: count, dtype: int64

Conteo de valores en la columna 'class':
class
Aves    85131
Name: count, dtype: int64

Conteo de valores en la columna 'order':
order
Passeriformes          38815
Anseriformes            7119
Charadriiformes         5420
Pelecaniformes          4245
Falconiformes           4024
Columbiformes           4013
Accipitriformes         3752
Piciformes              2505
Gruiformes              2215
Psittaciformes          2092
Apodiformes             1697
Strigiformes            1577
Suliformes              1516
Podicipediformes        1086
Cuculiformes             940
Procellariiformes        692
Ciconiiformes            651
Phoenicopteriformes      625
Coraciiformes            573
Sphenisciformes          318
Galliformes              287
Rheiformes               285
Tinamiformes             277
Caprimulgiformes         240
Trogoniformes             76
Nyctibiiformes            55
Cariamiformes             36
Name: count, dtype: int64

Conteo de valores en la columna 'family':
family
Tyrannidae        8687
Thraupidae        7986
Anatidae          6636
Furnariidae       4685
Falconidae        4024
                  ...
Rostratulidae        4
Grallariidae         3
Formicariidae        3
Pelecanoididae       3
Conopophagidae       3
Name: count, Length: 81, dtype: int64

Conteo de valores en la columna 'genus':
genus
Mimus           1899
Turdus          1805
Caracara        1660
Anas            1632
Zonotrichia     1630
                ...
Cochlearius        1
Nyctiphrynus       1
Lurocalis          1
Garrodia           1
Aphrodroma         1
Name: count, Length: 496, dtype: int64

Conteo de valores en la columna 'species':
species
Caracara plancus          1660
Zonotrichia capensis      1630
Pitangus sulphuratus      1580
Furnarius rufus           1418
Mimus saturninus          1406
                          ...
Euphonia cyanocephala        1
Colibri serrirostris         1
Elaenia mesoleuca            1
Nystalus striatipectus       1
Leucocarbo albiventer        1
Name: count, Length: 885, dtype: int64

Conteo de valores en la columna 'taxonRank':
taxonRank
SPECIES       82440
GENUS          1623
VARIETY         510
SUBSPECIES      366
FORM            175
FAMILY           17
Name: count, dtype: int64

Conteo de valores en la columna 'verbatimScientificName':
verbatimScientificName
Zonotrichia capensis           1606
Pitangus sulphuratus           1580
Caracara plancus               1578
Furnarius rufus                1418
Mimus saturninus               1406
                               ...
Herpsilochmus atricapillus        1
Phoebetria fusca                  1
Cacicus haemorrhous affinis       1
Haplospiza unicolor               1
Dendrocolaptes picumnus           1
Name: count, Length: 987, dtype: int64

Conteo de valores en la columna 'locality':
locality
Ushuaia                                           352
Ushuaia - Bahia Encerrada                         142
Tierra del Fuego NP                               115
Parque Nacional Los Glaciares                      78
Buenos Aires - Reserva Ecologica Costanera Sur     72
                                                 ...
Quebrada del Condorito NP                           1
Los Cardones NP                                     1
Berduc, Colón, Entre Ríos                           1
Refugio de Vida Silvestre Marahué                   1
Reserva ecologica costanera Sur                     1
Name: count, Length: 219, dtype: int64

Conteo de valores en la columna 'stateProvince':
stateProvince
Buenos Aires                       19105
La Pampa                           13162
Santa Fe                            9677
Ciudad de Buenos Aires              9045
Entre Ríos                          5656
Misiones                            4222
Córdoba                             3602
Tierra del Fuego                    3080
Santa Cruz                          1823
Jujuy                               1597
Río Negro                           1532
Formosa                             1430
Corrientes                          1428
Catamarca                           1298
Neuquén                             1298
Chubut                              1240
Tucumán                             1014
Mendoza                              950
San Luis                             857
Salta                                845
Autonomous City of Buenos Aires      453
Chaco                                351
Santiago del Estero                  278
San Juan                             237
La Rioja                             173
Buenos Aires (Province)              172
Santa Cruz Province, Argentina        31
Paraná                                23
Tierra del Fuego Province              7
Magallanes y Antártica Chilena         7
Artigas                                7
Asunción                               3
Rio Negro                              3
Alto Paraná                            2
Name: count, dtype: int64

Conteo de valores en la columna 'individualCount':
individualCount
1.0      713
2.0      174
3.0       56
4.0       56
10.0      36
5.0       33
20.0      24
8.0       15
6.0       14
30.0      14
40.0      13
50.0       9
15.0       9
25.0       9
12.0       8
100.0      6
7.0        6
9.0        4
60.0       4
23.0       3
35.0       3
16.0       2
70.0       2
80.0       2
90.0       2
13.0       1
19.0       1
14.0       1
11.0       1
65.0       1
140.0      1
250.0      1
500.0      1
75.0       1
18.0       1
Name: count, dtype: int64

Conteo de valores en la columna 'decimalLatitude':
decimalLatitude
-35.659324    2446
-34.607529     683
-37.368794     493
-32.068966     450
-34.951767     346
              ...
-34.541384       1
-34.393358       1
-38.815637       1
-28.541267       1
-32.839062       1
Name: count, Length: 56811, dtype: int64

Conteo de valores en la columna 'decimalLongitude':
decimalLongitude
-63.757789    2448
-58.352207     683
-64.599867     494
-60.638297     452
-57.904513     346
              ...
-57.690578       1
-60.980179       1
-58.354101       1
-57.863934       1
-57.577529       1
Name: count, Length: 57178, dtype: int64

Conteo de valores en la columna 'coordinateUncertaintyInMeters':
coordinateUncertaintyInMeters
15.0      3436
4.0       3368
31.0      3164
8.0       3136
2.0       3074
          ...
3180.0       1
1571.0       1
1576.0       1
2983.0       1
7020.0       1
Name: count, Length: 3000, dtype: int64

Conteo de valores en la columna 'eventDate':
eventDate
2025-03-22          104
2025-11-15           95
2025-03-21           73
2025-12-13           64
2025-03-04           59
                   ...
2025-12-03            1
2025-04-16            1
2025-12-10            1
2025-01-31T19:39      1
2025-04-22T08:27      1
Name: count, Length: 67683, dtype: int64

Conteo de valores en la columna 'day':
day
1     4549
2     4092
10    3724
3     3625
8     3603
11    3474
4     3208
6     3203
9     2999
15    2993
18    2826
7     2717
12    2716
19    2705
13    2648
26    2609
16    2587
20    2573
5     2464
28    2430
14    2402
22    2353
23    2290
21    2195
17    2181
25    2180
24    2104
29    2061
31    1956
30    1893
27    1771
Name: count, dtype: int64

Conteo de valores en la columna 'month':
month
1     9945
11    9269
7     8345
10    8333
8     7369
3     6628
9     6613
12    6302
5     6062
4     6014
2     5709
6     4542
Name: count, dtype: int64

Conteo de valores en la columna 'year':
year
2025    85131
Name: count, dtype: int64

Conteo de valores en la columna 'basisOfRecord':
basisOfRecord
HUMAN_OBSERVATION      85117
MACHINE_OBSERVATION       14
Name: count, dtype: int64

Conteo de valores en la columna 'institutionCode':
institutionCode
iNaturalist         83164
NABU|naturgucker       62
Name: count, dtype: int64

Conteo de valores en la columna 'collectionCode':
collectionCode
Observations               83164
NABU|naturgucker              62
Wildlife sounds - Birds       55
Name: count, dtype: int64

Conteo de valores en la columna 'mediaType':
mediaType
StillImage                                                                                                                                                                                                                                                                                                                                                                                                                57320
StillImage;StillImage                                                                                                                                                                                                                                                                                                                                                                                                     12039
StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                                                                                                           5402
StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                                                                                                2377
StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                                                                                     1128
Sound                                                                                                                                                                                                                                                                                                                                                                                                                       840
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                                                                           656
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                                                                400
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                                                     272
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                                          140
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                               109
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                                     72
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                  51
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                                          45
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                               40
Sound;Sound                                                                                                                                                                                                                                                                                                                                                                                                                  38
StillImage;StillImage;Sound                                                                                                                                                                                                                                                                                                                                                                                                  36
Sound;StillImage                                                                                                                                                                                                                                                                                                                                                                                                             32
Sound;StillImage;StillImage                                                                                                                                                                                                                                                                                                                                                                                                  29
StillImage;Sound                                                                                                                                                                                                                                                                                                                                                                                                             28
StillImage;Sound;StillImage                                                                                                                                                                                                                                                                                                                                                                                                  25
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                              23
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                         22
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                        21
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                   19
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                                                                                    18
StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage;StillImage                                                                                                                                                                                                             12
Sound;Sound;Sound                                                                                                                                                                                                                                                                                                                                                                                                             8

In [52]:
# Eliminar columnas de reino, filo y clase (son todas iguales ya que son aves)
df.drop(columns=['kingdom', 'phylum', 'class'], inplace=True)

# Eliminar columna locality (>90% de nulos)
df.drop(columns=['locality'], inplace=True)

# Eliminar otras columnas no útiles
df.drop(columns=['basisOfRecord', 'institutionCode', 'collectionCode',
                 'mediaType'], inplace=True)

# Verificar las columnas restantes y sus valores no nulos
print("DataFrame después de eliminar columnas con todos los valores nulos:")
print(df.info())

DataFrame después de eliminar columnas con todos los valores nulos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85131 entries, 0 to 85130
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order                          85131 non-null  object
 1   family                         85131 non-null  object
 2   genus                          85114 non-null  object
 3   species                        83491 non-null  object
 4   taxonRank                      85131 non-null  object
 5   verbatimScientificName         85131 non-null  object
 6   stateProvince                  84608 non-null  object
 7   individualCount                1227 non-null   float64
 8   decimalLatitude                85117 non-null  float64
 9   decimalLongitude               85117 non-null  float64
 10  coordinateUncertaintyInMeters  67714 non-null  float64
 11  eventDate                      85131 non-null  object
 12  day                            85131 non-null  int64
 13  month                          85131 non-null  int64
 14  year                           85131 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 9.7+ MB
None

In [53]:
# Eliminar registros con clasificaciones atípicas en taxonRank
df = df.loc[df["taxonRank"] != 'FAMILY']

# Asignar el valor de scientificName a registros sin valor en species
df.loc[df['species'].isnull(), 'species'] = df['verbatimScientificName']

# Eliminar columna taxonRank
df.drop(columns=['taxonRank', 'verbatimScientificName'], inplace=True)

# Verificar las columnas restantes y sus valores no nulos
print("DataFrame después de tratamiento de taxonRank:")
print(df.info())
for columna in df.columns:
    conteo = df[columna].value_counts()
    print(f"\nConteo de valores en la columna '{columna}':")
    print(conteo)

DataFrame después de tratamiento de taxonRank:
<class 'pandas.core.frame.DataFrame'>
Index: 85114 entries, 0 to 85130
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order                          85114 non-null  object
 1   family                         85114 non-null  object
 2   genus                          85114 non-null  object
 3   species                        85114 non-null  object
 4   stateProvince                  84591 non-null  object
 5   individualCount                1227 non-null   float64
 6   decimalLatitude                85100 non-null  float64
 7   decimalLongitude               85100 non-null  float64
 8   coordinateUncertaintyInMeters  67703 non-null  float64
 9   eventDate                      85114 non-null  object
 10  day                            85114 non-null  int64
 11  month                          85114 non-null  int64
 12  year                           85114 non-null  int64
dtypes: float64(4), int64(3), object(6)
memory usage: 11.1+ MB
None

Conteo de valores en la columna 'order':
order
Passeriformes          38815
Anseriformes            7102
Charadriiformes         5420
Pelecaniformes          4245
Falconiformes           4024
Columbiformes           4013
Accipitriformes         3752
Piciformes              2505
Gruiformes              2215
Psittaciformes          2092
Apodiformes             1697
Strigiformes            1577
Suliformes              1516
Podicipediformes        1086
Cuculiformes             940
Procellariiformes        692
Ciconiiformes            651
Phoenicopteriformes      625
Coraciiformes            573
Sphenisciformes          318
Galliformes              287
Rheiformes               285
Tinamiformes             277
Caprimulgiformes         240
Trogoniformes             76
Nyctibiiformes            55
Cariamiformes             36
Name: count, dtype: int64

Conteo de valores en la columna 'family':
family
Tyrannidae        8687
Thraupidae        7986
Anatidae          6619
Furnariidae       4685
Falconidae        4024
                  ...
Rostratulidae        4
Grallariidae         3
Formicariidae        3
Pelecanoididae       3
Conopophagidae       3
Name: count, Length: 81, dtype: int64

Conteo de valores en la columna 'genus':
genus
Mimus           1899
Turdus          1805
Caracara        1660
Anas            1632
Zonotrichia     1630
                ...
Cochlearius        1
Nyctiphrynus       1
Lurocalis          1
Garrodia           1
Aphrodroma         1
Name: count, Length: 496, dtype: int64

Conteo de valores en la columna 'species':
species
Caracara plancus          1660
Zonotrichia capensis      1630
Pitangus sulphuratus      1580
Furnarius rufus           1418
Mimus saturninus          1406
                          ...
Pelecanoides urinatrix       1
Elaenia mesoleuca            1
Grallaria albigula           1
Phoebetria fusca             1
Leucocarbo albiventer        1
Name: count, Length: 903, dtype: int64

Conteo de valores en la columna 'stateProvince':
stateProvince
Buenos Aires                       19100
La Pampa                           13162
Santa Fe                            9677
Ciudad de Buenos Aires              9035
Entre Ríos                          5656
Misiones                            4222
Córdoba                             3602
Tierra del Fuego                    3080
Santa Cruz                          1823
Jujuy                               1597
Río Negro                           1532
Formosa                             1430
Corrientes                          1428
Catamarca                           1298
Neuquén                             1296
Chubut                              1240
Tucumán                             1014
Mendoza                              950
San Luis                             857
Salta                                845
Autonomous City of Buenos Aires      453
Chaco                                351
Santiago del Estero                  278
San Juan                             237
La Rioja                             173
Buenos Aires (Province)              172
Santa Cruz Province, Argentina        31
Paraná                                23
Tierra del Fuego Province              7
Magallanes y Antártica Chilena         7
Artigas                                7
Asunción                               3
Rio Negro                              3
Alto Paraná                            2
Name: count, dtype: int64

Conteo de valores en la columna 'individualCount':
individualCount
1.0      713
2.0      174
3.0       56
4.0       56
10.0      36
5.0       33
20.0      24
8.0       15
6.0       14
30.0      14
40.0      13
50.0       9
15.0       9
25.0       9
12.0       8
100.0      6
7.0        6
9.0        4
60.0       4
23.0       3
35.0       3
16.0       2
70.0       2
80.0       2
90.0       2
13.0       1
19.0       1
14.0       1
11.0       1
65.0       1
140.0      1
250.0      1
500.0      1
75.0       1
18.0       1
Name: count, dtype: int64

Conteo de valores en la columna 'decimalLatitude':
decimalLatitude
-35.659324    2446
-34.607529     682
-37.368794     493
-32.068966     450
-34.951767     346
              ...
-34.794186       1
-33.217087       1
-38.083181       1
-35.923465       1
-27.309310       1
Name: count, Length: 56801, dtype: int64

Conteo de valores en la columna 'decimalLongitude':
decimalLongitude
-63.757789    2448
-58.352207     682
-64.599867     494
-60.638297     452
-57.904513     346
              ...
-59.249821       1
-65.272219       1
-58.644187       1
-54.564042       1
-72.255025       1
Name: count, Length: 57169, dtype: int64

Conteo de valores en la columna 'coordinateUncertaintyInMeters':
coordinateUncertaintyInMeters
15.0      3435
4.0       3368
31.0      3164
8.0       3135
2.0       3074
          ...
3180.0       1
1571.0       1
1576.0       1
2983.0       1
7020.0       1
Name: count, Length: 3000, dtype: int64

Conteo de valores en la columna 'eventDate':
eventDate
2025-03-22             104
2025-11-15              95
2025-03-21              73
2025-12-13              64
2025-03-04              59
                      ...
2025-10-02T11:19         1
2025-09-04T13:49         1
2025-11-07T10:03:44      1
2025-11-28T09:28         1
2025-01-06T18:06:37      1
Name: count, Length: 67670, dtype: int64

Conteo de valores en la columna 'day':
day
1     4549
2     4092
10    3724
3     3625
8     3603
11    3473
4     3208
6     3202
9     2998
15    2990
18    2826
7     2717
12    2716
19    2704
13    2648
26    2608
16    2587
20    2573
5     2462
28    2430
14    2401
22    2352
23    2290
21    2192
17    2180
25    2180
24    2104
29    2061
31    1956
30    1892
27    1771
Name: count, dtype: int64

Conteo de valores en la columna 'month':
month
1     9943
11    9265
7     8345
10    8331
8     7369
3     6627
9     6610
12    6300
5     6060
4     6014
2     5708
6     4542
Name: count, dtype: int64

Conteo de valores en la columna 'year':
year
2025    85114
Name: count, dtype: int64

In [54]:
df.to_csv('dataset-filtrado.csv', index=False)

# Imputación de valores para reemplazar nulos

In [55]:
# Media
media = df["coordinateUncertaintyInMeters"].mean()

# Deciles (quantile divide en percentiles, 0.1=10%, 0.2=20%, etc.)
deciles = df["coordinateUncertaintyInMeters"].quantile([i/10 for i in range(1,10)])

print("Media:", media)
print("\nDeciles:")
print(deciles)

Media: 4494.493345937403

Deciles:
0.1       4.0
0.2      13.0
0.3      31.0
0.4      61.0
0.5     139.0
0.6     240.0
0.7     555.0
0.8    2503.0
0.9    6716.6
Name: coordinateUncertaintyInMeters, dtype: float64

In [56]:
# Asignar valor 1 en individualCount a todos los registros sin especificarlo
df["individualCount"] = df["individualCount"].fillna(1)

# Asignar la mediana en uncertainity para valores nulos
df["coordinateUncertaintyInMeters"] = df["coordinateUncertaintyInMeters"].fillna(df["coordinateUncertaintyInMeters"].median())

# Tratamiento de fechas y horas

In [57]:
# Fragmento: extrae hora desde df["eventDate"] y crea df["time"]
# Asume que `df` y `pd` ya están definidos en el notebook.
# Cambia TIME_FORMAT o CONVERT_TO_TZ según necesites.

import re

TIME_FORMAT = "HH:MM"        # opciones: "HH:MM:SS" o "HH:MM"
CONVERT_TO_TZ = "America/Argentina/Buenos_Aires"            # e.g. "America/Argentina/Buenos_Aires" o None

_presence_re = re.compile(r'[T\s]\d{2}:\d{2}')
_extract_re = re.compile(r'[T\s](\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?)')

def extract_time_from_eventdate(val, time_format=TIME_FORMAT, convert_to_tz=CONVERT_TO_TZ):
    if pd.isna(val):
        return pd.NA
    s = str(val).strip()
    # si no hay indicio de tiempo (ni 'T' ni espacio seguido de HH:MM) -> NA
    if not _presence_re.search(s):
        return pd.NA

    # intento principal: pandas (maneja Z y offsets)
    dt = pd.to_datetime(s, errors="coerce", utc=True)
    if pd.isna(dt):
        # fallback por regex (captura tras 'T' o espacio)
        m = _extract_re.search(s)
        if not m:
            return pd.NA
        time_str = m.group(1).split('.')[0]  # quitar fracciones de segundo si existen
        # normalizar según formato pedido
        if time_format == "HH:MM":
            return time_str[:5]
        # si faltan segundos, agregar ":00"
        return time_str if time_str.count(":") == 2 else time_str + ":00"

    # si se pidió conversión de zona horaria la aplicamos
    if convert_to_tz:
        try:
            dt = dt.tz_convert(convert_to_tz)
        except Exception:
            return pd.NA

    t = dt.time().replace(microsecond=0)
    return t.strftime("%H:%M") if time_format == "HH:MM" else t.strftime("%H:%M:%S")

def time_to_range(t):
    """
    Convierte un valor de df['time'] (p. ej. "19:18:15" o datetime.time) a:
      1 -> 00:00-05:59
      2 -> 06:00-11:59
      3 -> 12:00-17:59
      4 -> 18:00-23:59
    Devuelve pd.NA si t es NaN, vacío o no parseable.
    """
    if pd.isna(t):
        return pd.NA
    try:
        # Si es un objeto time/Timestamp con atributo hour
        if hasattr(t, "hour"):
            hour = int(t.hour)
        else:
            s = str(t).strip()
            if not s:
                return pd.NA
            hour = int(s.split(":")[0])
    except Exception:
        return pd.NA

    if 0 <= hour < 6:
        return 1
    if 6 <= hour < 12:
        return 2
    if 12 <= hour < 18:
        return 3
    if 18 <= hour < 24:
        return 4
    return pd.NA

# Aplicar al DataFrame (vectorizado con apply)
df["time"] = df["eventDate"].apply(lambda v: extract_time_from_eventdate(v, TIME_FORMAT, CONVERT_TO_TZ))

# Eliminar columnas con time nulo
df.dropna(subset=["time"], inplace=True)

# Aplicación al DataFrame (usa dtype nullable Int64 para mantener NA)
df["timeRange"] = df["time"].apply(time_to_range).astype("Int64")

# Display the first few rows with the new 'time' column
display(df[['eventDate', 'time', 'timeRange']].head())

# Check for null values in the new 'time' column
print("\nNull values in 'time' column:")
print(df['time'].isnull().sum())

# Eliminar la columna eventDate
df.drop(columns=['eventDate'], inplace=True)

             eventDate   time  timeRange
0    2025-04-03T23:35Z  20:35          4
1    2025-04-03T23:33Z  20:33          4
2     2025-01-31T19:39  16:39          3
3  2025-07-12T17:20:42  14:20          3
4     2025-09-15T19:10  16:10          3

Null values in 'time' column:
0

In [58]:
import numpy as np

# Convertir la columna 'time' a formato de hora decimal
df['hour'] = df['time'].str.split(':').apply(lambda x: int(x[0]) + int(x[1])/60)

# Aplicar transformación cíclica para la hora del día
df['hour_cycle'] = np.cos(2 * np.pi * df['hour'] / 24)

# Mostrar las primeras filas con las nuevas columnas
display(df[['time', 'hour', 'hour_cycle']].head())

# Verificar los tipos de datos y valores no nulos
print("\nDataFrame después de agregar 'hour' y 'hour_cycle':")
print(df.info())

    time       hour  hour_cycle
0  20:35  20.583333    0.625923
1  20:33  20.550000    0.619094
2  16:39  16.650000   -0.346117
3  14:20  14.333333   -0.819152
4  16:10  16.166667   -0.461749

DataFrame después de agregar 'hour' y 'hour_cycle':
<class 'pandas.core.frame.DataFrame'>
Index: 82446 entries, 0 to 83898
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order                          82446 non-null  object
 1   family                         82446 non-null  object
 2   genus                          82446 non-null  object
 3   species                        82446 non-null  object
 4   stateProvince                  81990 non-null  object
 5   individualCount                82446 non-null  float64
 6   decimalLatitude                82446 non-null  float64
 7   decimalLongitude               82446 non-null  float64
 8   coordinateUncertaintyInMeters  82446 non-null  float64
 9   day                            82446 non-null  int64
 10  month                          82446 non-null  int64
 11  year                           82446 non-null  int64
 12  time                           82446 non-null  object
 13  timeRange                      82446 non-null  Int64
 14  hour                           82446 non-null  float64
 15  hour_cycle                     82446 non-null  float64
dtypes: Int64(1), float64(6), int64(3), object(6)
memory usage: 10.8+ MB
None

# Transformación de Provincias
Primero vamos a ver la cantidad de avistamientos que tenemos para cada provincia

In [59]:
conteo = df["stateProvince"].value_counts()

print(conteo)

stateProvince
Buenos Aires                       18777
La Pampa                           13142
Santa Fe                            9503
Ciudad de Buenos Aires              8858
Entre Ríos                          5496
Misiones                            4149
Córdoba                             3557
Tierra del Fuego                    2377
Santa Cruz                          1681
Jujuy                               1568
Río Negro                           1521
Corrientes                          1376
Neuquén                             1269
Formosa                             1242
Catamarca                           1235
Chubut                              1189
Mendoza                              934
Tucumán                              908
San Luis                             843
Salta                                803
Autonomous City of Buenos Aires      453
Chaco                                347
Santiago del Estero                  275
San Juan                             237
La Rioja                             170
Santa Cruz Province, Argentina        31
Paraná                                23
Tierra del Fuego Province              7
Magallanes y Antártica Chilena         7
Artigas                                7
Asunción                               3
Alto Paraná                            2
Name: count, dtype: int64

Ahora eliminamos las filas que contengan provincias que no correspondan a Argentina

In [60]:
# Eliminar columnas con stateProvince nulo
df.dropna(subset=["stateProvince"], inplace=True)

provincias_a_eliminar = ["Artigas", "Magallanes y Antártica Chilena", "Asunción"]

# Filtro para quitar esas filas
df = df[~df["stateProvince"].isin(provincias_a_eliminar)]

print(df["stateProvince"].value_counts())

stateProvince
Buenos Aires                       18777
La Pampa                           13142
Santa Fe                            9503
Ciudad de Buenos Aires              8858
Entre Ríos                          5496
Misiones                            4149
Córdoba                             3557
Tierra del Fuego                    2377
Santa Cruz                          1681
Jujuy                               1568
Río Negro                           1521
Corrientes                          1376
Neuquén                             1269
Formosa                             1242
Catamarca                           1235
Chubut                              1189
Mendoza                              934
Tucumán                              908
San Luis                             843
Salta                                803
Autonomous City of Buenos Aires      453
Chaco                                347
Santiago del Estero                  275
San Juan                             237
La Rioja                             170
Santa Cruz Province, Argentina        31
Paraná                                23
Tierra del Fuego Province              7
Alto Paraná                            2
Name: count, dtype: int64

Ahora reemplazamos algunos lugares por la provincia correspondiente

In [61]:
reemplazos = {
    "Buenos Aires (Province)": "Buenos Aires",
    "Santa Cruz Province, Argentina": "Santa Cruz",
    "Rio Negro":"Río Negro",
    "Alto Paraná": "Misiones",
    "Paraná": "Misiones",
    "Tierra del Fuego Province": "Tierra del Fuego",
    "Autonomous City of Buenos Aires": "Ciudad de Buenos Aires"
}

df.loc[:, "stateProvince"] = df["stateProvince"].replace(reemplazos)
print(df["stateProvince"].value_counts())

stateProvince
Buenos Aires              18777
La Pampa                  13142
Santa Fe                   9503
Ciudad de Buenos Aires     9311
Entre Ríos                 5496
Misiones                   4174
Córdoba                    3557
Tierra del Fuego           2384
Santa Cruz                 1712
Jujuy                      1568
Río Negro                  1521
Corrientes                 1376
Neuquén                    1269
Formosa                    1242
Catamarca                  1235
Chubut                     1189
Mendoza                     934
Tucumán                     908
San Luis                    843
Salta                       803
Chaco                       347
Santiago del Estero         275
San Juan                    237
La Rioja                    170
Name: count, dtype: int64

Luego vamos a asignarle un numero a cada provincia y creamos la columna llamada "provincia_num"

In [62]:
df["provincia_num"] = pd.factorize(df["stateProvince"])[0]

print(df.loc[:, ["stateProvince", "provincia_num"]].head(10))

   stateProvince  provincia_num
2       La Pampa              0
3   Buenos Aires              1
4          Salta              2
5       Santa Fe              3
6       Santa Fe              3
7       La Pampa              0
8     Entre Ríos              4
9       Misiones              5
10  Buenos Aires              1
11       Tucumán              6

# Tratamiento de year y day

Convertimos day, month, year e individualCount a int64, para respetar su naturaleza

In [63]:
# Convertir columnas a tipo int64
df['day'] = df['day'].astype('int64')
df['month'] = df['month'].astype('int64')
df['timeRange'] = df['timeRange'].astype('int64')
df['individualCount'] = df['individualCount'].astype('int64')

# Eliminar columnas year, time, stateProvince
df.drop(columns=['year', 'time', 'stateProvince'], inplace=True)

Agregamos una columna "day_of_year", que puede aportar al entrenamiento del modelo por la naturaleza cíclica de los días del año.

In [64]:
# Diccionario para mapear el mes al número acumulado de días antes de ese mes (en un año no bisiesto)
days_before_month = {
    1: 0,  # January
    2: 31, # February
    3: 59, # March
    4: 90, # April
    5: 120, # May
    6: 151, # June
    7: 181, # July
    8: 212, # August
    9: 243, # September
    10: 273, # October
    11: 304, # November
    12: 334  # December
}

# Calcular day_of_year
# Convert month and day to integers for dictionary lookup and calculation
df['day_of_year'] = df.apply(
    lambda row: days_before_month.get(int(row['month']), 0) + int(row['day']),
    axis=1
)

# Handle February 29th as the 60th day (as requested)
df.loc[(df['month'] == 2) & (df['day'] == 29), 'day_of_year'] = 60

# Verificar los cambios
print("DataFrame después de agregar la columna 'day_of_year':")
print(df[['day', 'month', 'day_of_year']].head())
print(df.info())

DataFrame después de agregar la columna 'day_of_year':
   day  month  day_of_year
2   31      1           31
3   12      7          193
4   15      9          258
5    6      7          187
6   13      7          194
<class 'pandas.core.frame.DataFrame'>
Index: 81973 entries, 2 to 83898
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order                          81973 non-null  object
 1   family                         81973 non-null  object
 2   genus                          81973 non-null  object
 3   species                        81973 non-null  object
 4   individualCount                81973 non-null  int64
 5   decimalLatitude                81973 non-null  float64
 6   decimalLongitude               81973 non-null  float64
 7   coordinateUncertaintyInMeters  81973 non-null  float64
 8   day                            81973 non-null  int64
 9   month                          81973 non-null  int64
 10  timeRange                      81973 non-null  int64
 11  hour                           81973 non-null  float64
 12  hour_cycle                     81973 non-null  float64
 13  provincia_num                  81973 non-null  int64
 14  day_of_year                    81973 non-null  int64
dtypes: float64(5), int64(6), object(4)
memory usage: 10.0+ MB
None

# Integración de dataset externo

In [65]:
!pip install geopandas rasterio

Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: rasterio in /usr/local/lib/python3.12/dist-packages (1.5.0)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from rasterio) (2.4.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rasterio) (25.4.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from rasterio) (2026.1.4)
Requirement already satisfied: click!=8.2.*,>=4.0 in /usr/local/lib/python3.12/dist-packages (from rasterio) (8.3.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from rasterio) (0.7.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from rasterio) (3.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [66]:
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio import features
from rasterio.warp import transform
from rasterio.mask import mask
import numpy as np
import os
from tqdm import tqdm

In [67]:
# Rasters (download once, then reuse)
# Use global rasters in GeoTIFF form (.tif)
PATH_ELEV = f'{DATA_DIR}/elevation_argentina.tif'
PATH_TEMP = f'{DATA_DIR}/mean_temp_argentina.tif'    # BIO1 = mean annual temperature
PATH_PREC = f'{DATA_DIR}/annual_prec_argentina.tif' # BIO12 = annual precipitation

In [68]:
# --- 1) Load coordinates ---

# Check your coordinate columns — adjust names if needed
lat_col, lon_col = 'decimalLatitude', 'decimalLongitude'

# Drop rows without valid coordinates
df = df.dropna(subset=[lat_col, lon_col])

# Convert to GeoDataFrame
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df[lon_col], df[lat_col]),
    crs="EPSG:4326"
)
gdf.head()

,order,family,genus,species,individualCount,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,day,month,timeRange,hour,hour_cycle,provincia_num,day_of_year,geometry
2,Passeriformes,Fringillidae,Spinus,Spinus magellanicus,1,-35.659324,-63.757789,4571.0,31,1,3,16.650000,-0.346117,0,31,POINT (-63.75779 -35.65932)
3,Apodiformes,Trochilidae,Leucochloris,Leucochloris albicollis,1,-34.491839,-58.479915,20.0,12,7,3,14.333333,-0.819152,1,193,POINT (-58.47992 -34.49184)
4,Passeriformes,Parulidae,Setophaga,Setophaga pitiayumi,1,-25.276728,-65.387564,2.0,15,9,3,16.166667,-0.461749,2,258,POINT (-65.38756 -25.27673)
5,Anseriformes,Anatidae,Anas,Anas flavirostris,1,-31.554500,-61.052494,139.0,6,7,2,8.483333,-0.605294,3,187,POINT (-61.05249 -31.5545)
6,Piciformes,Picidae,Melanerpes,Melanerpes cactorum,1,-30.197865,-61.165918,4.0,13,7,2,8.800000,-0.669131,3,194,POINT (-61.16592 -30.19786)

In [69]:
# --- 2) Function to sample raster values at points ---
def extract_raster_values(gdf, raster_path, col_name):
    with rasterio.open(raster_path) as src:
        # Ensure same CRS
        gdf = gdf.to_crs(src.crs)
        # Extract pixel value for each point
        values = []
        for geom in tqdm(gdf.geometry, desc=f"Extracting {col_name}"):
            try:
                for val in src.sample([(geom.x, geom.y)]):
                    values.append(val[0])
            except Exception:
                values.append(np.nan)
        gdf[col_name] = values
    return gdf

In [70]:
# --- 3) Add Elevation ---
gdf = extract_raster_values(gdf, PATH_ELEV, 'elevation_m')

# --- 4) Add Mean Annual Temperature (WorldClim BIO1) ---
gdf = extract_raster_values(gdf, PATH_TEMP, 'temp_annual_c')

# --- 5) Add Annual Precipitation (WorldClim BIO12) ---
gdf = extract_raster_values(gdf, PATH_PREC, 'precip_annual_mm')

Extracting elevation_m: 100%|██████████| 81973/81973 [00:32<00:00, 2538.93it/s]
Extracting temp_annual_c: 100%|██████████| 81973/81973 [00:18<00:00, 4397.45it/s]
Extracting precip_annual_mm: 100%|██████████| 81973/81973 [00:19<00:00, 4266.98it/s]

In [71]:
# --- 6) Inspect correlations / missingness ---
print(gdf[['elevation_m','temp_annual_c','precip_annual_mm']].describe())
print("Missing elevation:", gdf['elevation_m'].isna().mean())

gdf = gdf.replace([-32768, -3.4028235e+38, -3.4e+37], np.nan)
gdf = gdf.dropna(subset=['elevation_m', 'temp_annual_c', 'precip_annual_mm'])

print(gdf['elevation_m'].describe())
print(gdf['temp_annual_c'].describe())
print(gdf['precip_annual_mm'].describe())

gdf.drop(['geometry'], axis=1, inplace=True)

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:52: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/usr/local/lib/python3.12/dist-packages/pandas/core/nanops.py:1025: RuntimeWarning: overflow encountered in cast
  result = result.astype(dtype, copy=False)
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:52: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/usr/local/lib/python3.12/dist-packages/pandas/core/nanops.py:1025: RuntimeWarning: overflow encountered in cast
  result = result.astype(dtype, copy=False)

        elevation_m  temp_annual_c  precip_annual_mm
count  81973.000000   8.197300e+04      8.197300e+04
mean    -846.529138           -inf              -inf
std     5983.510693            inf               inf
min   -32768.000000  -3.400000e+38     -3.400000e+38
25%       10.000000   1.556250e+01      7.550000e+02
50%       58.000000   1.682917e+01      9.550000e+02
75%      164.000000   1.793750e+01      1.047000e+03
max     6700.000000   2.383750e+01      3.192000e+03
Missing elevation: 0.0
count    79215.000000
mean       264.869166
std        579.479893
min        -43.000000
25%         13.000000
50%         65.000000
75%        179.000000
max       6700.000000
Name: elevation_m, dtype: float64
count    79215.000000
mean        16.394686
std          3.501090
min        -15.770833
25%         15.845834
50%         17.112499
75%         18.008333
max         23.837500
Name: temp_annual_c, dtype: float64
count    79215.000000
mean       920.232361
std        321.536957
min         50.000000
25%        818.000000
50%        973.000000
75%       1049.000000
max       3192.000000
Name: precip_annual_mm, dtype: float64

# Exportación

In [72]:
gdf.to_csv(PATH_OUTPUT, index=False)
print(gdf.info())

for columna in df.columns:
    conteo = df[columna].value_counts()
    print(f"\nConteo de valores en la columna '{columna}':")
    print(conteo)

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 79215 entries, 2 to 83898
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order                          79215 non-null  object
 1   family                         79215 non-null  object
 2   genus                          79215 non-null  object
 3   species                        79215 non-null  object
 4   individualCount                79215 non-null  int64
 5   decimalLatitude                79215 non-null  float64
 6   decimalLongitude               79215 non-null  float64
 7   coordinateUncertaintyInMeters  79215 non-null  float64
 8   day                            79215 non-null  int64
 9   month                          79215 non-null  int64
 10  timeRange                      79215 non-null  int64
 11  hour                           79215 non-null  float64
 12  hour_cycle                     79215 non-null  float64
 13  provincia_num                  79215 non-null  int64
 14  day_of_year                    79215 non-null  int64
 15  elevation_m                    79215 non-null  float64
 16  temp_annual_c                  79215 non-null  float32
 17  precip_annual_mm               79215 non-null  float32
dtypes: float32(2), float64(6), int64(6), object(4)
memory usage: 10.9+ MB
None

Conteo de valores en la columna 'order':
order
Passeriformes          37709
Anseriformes            6839
Charadriiformes         5060
Pelecaniformes          4103
Columbiformes           3914
Falconiformes           3852
Accipitriformes         3660
Piciformes              2436
Gruiformes              2168
Psittaciformes          2033
Apodiformes             1664
Strigiformes            1544
Suliformes              1453
Podicipediformes        1071
Cuculiformes             915
Ciconiiformes            632
Phoenicopteriformes      616
Coraciiformes            554
Procellariiformes        283
Galliformes              278
Rheiformes               276
Tinamiformes             272
Sphenisciformes          257
Caprimulgiformes         223
Trogoniformes             74
Nyctibiiformes            52
Cariamiformes             35
Name: count, dtype: int64

Conteo de valores en la columna 'family':
family
Tyrannidae        8432
Thraupidae        7812
Anatidae          6373
Furnariidae       4493
Icteridae         3924
                  ...
Grallariidae         3
Formicariidae        3
Conopophagidae       3
Hydrobatidae         1
Pelecanoididae       1
Name: count, Length: 81, dtype: int64

Conteo de valores en la columna 'genus':
genus
Mimus             1868
Turdus            1769
Anas              1613
Caracara          1589
Pitangus          1550
                  ...
Nyctiphrynus         1
Lurocalis            1
Pelecanoides         1
Ramphotrigon         1
Leuconotopicus       1
Name: count, Length: 486, dtype: int64

Conteo de valores en la columna 'species':
species
Caracara plancus             1589
Pitangus sulphuratus         1549
Zonotrichia capensis         1499
Furnarius rufus              1388
Mimus saturninus             1381
                             ...
Pelecanoides magellani          1
Ramphotrigon megacephalum       1
Leuconotopicus fumigatus        1
Cranioleuca obsoleta            1
Sporophila bouvreuil            1
Name: count, Length: 873, dtype: int64

Conteo de valores en la columna 'individualCount':
individualCount
1     81941
2        13
3         8
4         3
6         2
8         2
12        1
5         1
19        1
23        1
Name: count, dtype: int64

Conteo de valores en la columna 'decimalLatitude':
decimalLatitude
-35.659324    2446
-34.607529     671
-37.368794     493
-32.068966     450
-34.951767     346
              ...
-34.577862       1
-25.680813       1
-34.585131       1
-34.589517       1
-34.598783       1
Name: count, Length: 54539, dtype: int64

Conteo de valores en la columna 'decimalLongitude':
decimalLongitude
-63.757789    2448
-58.352207     671
-64.599867     494
-60.638297     452
-57.904513     346
              ...
-58.578608       1
-68.331057       1
-58.951147       1
-71.360417       1
-58.361227       1
Name: count, Length: 54907, dtype: int64

Conteo de valores en la columna 'coordinateUncertaintyInMeters':
coordinateUncertaintyInMeters
139.0       17181
15.0         3360
4.0          3246
31.0         3137
8.0          3079
            ...
43269.0         1
1302.0          1
2190.0          1
2078.0          1
385959.0        1
Name: count, Length: 2892, dtype: int64

Conteo de valores en la columna 'day':
day
1     4432
2     3954
10    3630
3     3503
8     3502
11    3374
6     3108
4     3076
9     2904
15    2854
18    2761
7     2664
19    2611
13    2547
12    2537
16    2484
20    2480
26    2469
5     2376
28    2346
14    2265
23    2217
22    2163
25    2122
17    2097
21    2049
24    2029
29    2021
31    1877
30    1823
27    1698
Name: count, dtype: int64

Conteo de valores en la columna 'month':
month
1     9616
11    8535
7     8276
10    8174
8     7285
9     6506
12    6041
5     5941
3     5873
4     5833
2     5386
6     4507
Name: count, dtype: int64

Conteo de valores en la columna 'timeRange':
timeRange
2    42351
3    29684
1     8591
4     1347
Name: count, dtype: int64

Conteo de valores en la columna 'hour':
hour
7.050000     194
7.283333     188
7.066667     187
7.500000     187
9.666667     185
            ...
21.950000      1
22.166667      1
0.733333       1
1.866667       1
22.800000      1
Name: count, Length: 1364, dtype: int64

Conteo de valores en la columna 'hour_cycle':
hour_cycle
-0.382683    234
-0.927184    234
-0.999962    228
-0.995396    227
-0.998630    224
            ...
 0.857167      1
 0.948324      1
 0.740218      1
 0.882948      1
 0.951057      1
Name: count, Length: 1258, dtype: int64

Conteo de valores en la columna 'provincia_num':
provincia_num
1     18777
0     13142
3      9503
7      9311
4      5496
5      4174
13     3557
9      2384
15     1712
11     1568
20     1521
12     1376
21     1269
8      1242
10     1235
18     1189
14      934
6       908
19      843
2       803
16      347
22      275
17      237
23      170
Name: count, dtype: int64

Conteo de valores en la columna 'day_of_year':
day_of_year
284    1168
130    1002
305     939
32      795
214     745
       ...
156      52
86       52
181      49
105      40
147      23
Name: count, Length: 365, dtype: int64